### ISSUE TITLE
Error when no function specified

### ISSUE THREAD

**Issue by emurphy-9** [LasaleFamine/runnable-exports#1]
Firstly, thanks for the repo, I really like your module and it's exactly the sort of thing I was looking for.
 
Unfortunately, if the user runs the JS file without specifying a function they get this error: `Error: RUNNABLE-EXPORTS: can't run your command:`

It would be nice if it instead suggested to the user which commands can be run, similar to the original make-runnable project. Currently the output is a bit ugly especially if it's being used in production. Even if this was a configurable option that would be great.

**Comment by emurphy-9** [comment]
@LasaleFamine Sure I can look into it, I haven't delved into your code but I can have a go. 😄

**Comment by emurphy-9** [comment]
Doesn't look too bad, I've got a very basic thing working right not.

Just wondering though are your tests currently working because after I did `yarn install` the tests that throw errors were failing. I fixed them by changing the `error.message.search` to `error.stderr.search` but I want to check that it's broken for you too.

Also I noticed that if you pass in multiple args to an export from the command line that it becomes an array. If we just add in the spread operator (`...`) we can separate the args again when we pass them to the exported function, just like make-runnable does. i.e. 
`
const exportedFunc (args) => {
 let var1 = args[0];
 let var2 = args[1];
 // etc.
}
`

becomes: 
`
const exportedFunc = (var1, var2) => {
}
`

Personally I prefer this method, what do you think?

**Comment by LasaleFamine** [comment]
I don't know actually about the error in test, I need to check. Anyway with a PR the tests will run on Travis, so we can double check on different versions of Node.

The change make sense to me. The code was written time ago, so feel free to make some improvements if you want. 😄

**Comment by emurphy-9** [comment]
Good stuff, I'll bash it out over the next few days anyway, make some new tests etc. 😄

**Comment by LasaleFamine** [comment]
And released 🎉 I've added you as contributor within the package.json. Thanks again, great work 👍
